### ISSUE TITLE
Nix installation instructions

### ISSUE THREAD

**Issue by eraserhd** [mayjs/openscad.kak#1]
Hi, I made a PR to package this in Nix: https://github.com/NixOS/nixpkgs/pull/103969

I'll make a PR for Nix installation instructions when it is in.

Thanks for this!

**Comment by mayjs** [comment]
Hey, thank you for your input! I'll gladly accept your PR when it's ready.

Let me know if you notice anything wrong with this plugin, I don't think it has had any users besides me until now.
